### ISSUE TITLE
[not an issue] did you see this wwdc / physics based rendering with scenekit?

### ISSUE THREAD

**Issue by johndpope** [daniel-beard/DBRaytracer#1]
https://www.youtube.com/watch?v=xtl-zOdoD7Y

**Comment by daniel-beard** [comment]
@johndpope I saw part of it, but thanks for the link! Definitely have to play more with SceneKit. 👍

**Comment by johndpope** [comment]
fyi - https://github.com/FernandoDoming/CodinGame/blob/c9d88791b514d27f258d32f7dc56c4f12cf0f8fc/Attractors/Attractors/GameViewController.swift
